import os
import hashlib
import sys

def calculate_sha256(filepath):
    sha256_hash = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None

def generate_manifest(root_folder):
    root_folder = os.path.abspath(root_folder)
    
    index_path = os.path.join(root_folder, "index.html")
    if not os.path.isfile(index_path):
        print("❌ Error: 'index.html' not found in the specified directory.")
        print(f"Checked path: {index_path}")
        return

    print(f"✅ 'index.html' found. Scanning directory...")

    manifest_entries = []

    for root, dirs, files in os.walk(root_folder):
        for file in files:
            if file == "cache.manifest" or file.startswith(".") or file.endswith(".py"):
                continue

            full_path = os.path.join(root, file)
            
            relative_path = os.path.relpath(full_path, root_folder)
            
            relative_path = relative_path.replace(os.sep, '/')

            file_hash = calculate_sha256(full_path)
            
            if file_hash:
                entry = f"{relative_path} #{file_hash}"
                manifest_entries.append(entry)
                print(f"Processed: {relative_path}")

    manifest_entries.sort()

    manifest_content = "CACHE MANIFEST\n"
    manifest_content += f"# Generated by Python Script\n"
    manifest_content += f"# Date: {os.path.basename(root_folder)}\n\n"

    manifest_content += "\n".join(manifest_entries)

    manifest_content += "\n\nNETWORK:\n*"

    output_path = os.path.join(root_folder, "cache.manifest")
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(manifest_content)
        print("\n" + "="*50)
        print(f"✅ SUCCESS! 'cache.manifest' created successfully.")
        print(f"📍 Location: {output_path}")
        print(f"📄 Total Files Cached: {len(manifest_entries)}")
        print("="*50)
    except Exception as e:
        print(f"❌ Error writing manifest file: {e}")

if __name__ == "__main__":
    print("--- PS5 Host Manifest Generator ---")
    folder_path = input("Enter the path to your host folder: ").replace("& '","").replace("'",'"').strip().strip('"')
    
    if os.path.isdir(folder_path):
        generate_manifest(folder_path)
    else:
        print("❌ Invalid directory path.")
